# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks: []
builds:
  - id: AnimeGo
    main: cmd/animego/main.go
    binary: AnimeGo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7
    ldflags:
      - -s -w -X "github.com/wetor/AnimeGo/cmd/common.version={{.Tag}}" -X "github.com/wetor/AnimeGo/cmd/common.buildTime={{.Date}}"

  - id: AnimeGo-plugin
    main: cmd/plugin/main.go
    binary: AnimeGo-plugin
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/wetor/AnimeGo/cmd/common.version={{.Tag}}" -X "github.com/wetor/AnimeGo/cmd/common.buildTime={{.Date}}"

dockers:
  -
    id: AnimeGo-Docker
    goos: linux
    goarch: amd64
    ids:
      - AnimeGo
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "wetor/animego:latest"
      - "wetor/animego:{{ .Tag }}"
      - "ghcr.io/wetor/animego:latest"
      - "ghcr.io/wetor/animego:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

archives:
  - name_template: >-
      {{- .Binary }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    allow_different_binary_count: true
    builds:
      - AnimeGo
      - AnimeGo-plugin
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'