// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/wetor/AnimeGo",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://www.mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bolt": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取Bolt数据库的Bucket列表，或指定Bucket下的key列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bolt"
                ],
                "summary": "获取Bolt数据库的Bucket列表或key列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当type=key时，需要此参数",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "bolt",
                        "description": "bolt, bolt_sub",
                        "name": "db",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "bucket, key",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BoltListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/bolt/value": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取Bolt数据库指定Bucket和key所储存的值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bolt"
                ],
                "summary": "获取Bolt数据库的值",
                "parameters": [
                    {
                        "type": "string",
                        "name": "bucket",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bolt",
                        "description": "bolt, bolt_sub",
                        "name": "db",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BoltGetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除Bolt数据库指定Bucket和key所储存的值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bolt"
                ],
                "summary": "删除Bolt数据库的值",
                "parameters": [
                    {
                        "type": "string",
                        "name": "bucket",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bolt",
                        "description": "bolt, bolt_sub",
                        "name": "db",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BoltGetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/config": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取AnimeGo的配置文件内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取设置",
                "parameters": [
                    {
                        "type": "string",
                        "default": "raw",
                        "description": "Key 使用路径方式获取指定yaml key内容\n  [暂不支持] 如 setting.save_path, advanced.download.queue_max_num\n  all 获取所有配置项，json格式\n  default 获取默认值配置项，json格式\n  comment 获取所有配置项的注释文本，json格式\n  raw 获取所有配置项，yaml文件内容，base64编码",
                        "name": "key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新AnimeGo的配置文件内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "更新设置",
                "parameters": [
                    {
                        "description": "更新配置文件",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConfigPutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/config/file": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取AnimeGo的配置文件文本内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取配置文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "写入AnimeGo的配置文件文本内容",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "写入配置文件",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "备份旧的配置",
                        "name": "backup",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "配置文件文本",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/manager": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加下载项到AnimeGo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager"
                ],
                "summary": "添加下载项",
                "parameters": [
                    {
                        "description": "下载项信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddItemsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/plugin/config": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "从AnimeGo中获取当前插件的配置\n插件名为不包含 'plugin' 的路径\n插件名可以忽略'.js'后缀；插件名也可以使用上层文件夹名，会自动寻找文件夹内部的 'main.js' 或 'plugin.js'\n如传入 'test'，会依次尝试寻找 'plugin/test/main.js', 'plugin/test/plugin.js', 'plugin/test.js'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "获取插件配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "插件信息",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "将当前插件的配置发送给AnimeGo并保存\n插件名为不包含 'plugin' 的路径\n插件名可以忽略'.py'后缀；插件名也可以使用上层文件夹名，会自动加载文件夹内部的 'main.py'\n如设置为 'plugin/test'，会依次尝试加载 'plugin/test/main.py', 'plugin/test.py'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "发送插件配置",
                "parameters": [
                    {
                        "description": "插件信息，data为base64编码后的json文本",
                        "name": "plugin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PluginConfigUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/plugin/manager/dir": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取插件文件夹中指定文件夹的文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "获取插件文件列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DirResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建插件文件夹中的文件夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "创建文件夹",
                "parameters": [
                    {
                        "description": "创建文件夹信息",
                        "name": "path",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PathRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除插件文件夹中指定文件文件夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "删除文件夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/plugin/manager/file": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取插件文件夹中指定文件的内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "获取插件文件内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建或修改插件文件夹中指定文件",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "创建或修改插件文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "文件内容",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除插件文件夹中指定插件文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "删除插件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/plugin/manager/rename": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "重命名插件文件夹中的文件或文件夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugin"
                ],
                "summary": "重命名文件或文件夹",
                "parameters": [
                    {
                        "description": "重命名信息",
                        "name": "path",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NewPathRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/rss": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "将待下载项组合成rss发送给AnimeGo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rss"
                ],
                "summary": "发送下载项",
                "parameters": [
                    {
                        "description": "组合的rss信息",
                        "name": "rss",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SelectEpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "300": {
                        "description": "Multiple Choices",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Pong",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/sha256": {
            "get": {
                "description": "SHA256计算",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "SHA256计算",
                "parameters": [
                    {
                        "type": "string",
                        "description": "原文本",
                        "name": "access_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/websocket/log": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "监听日志接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "WebSocket日志监听接口",
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddItemsRequest": {
            "type": "object",
            "required": [
                "data",
                "source"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "torrent"
                        ],
                        "properties": {
                            "info": {
                                "type": "object",
                                "additionalProperties": {}
                            },
                            "torrent": {
                                "type": "string"
                            }
                        }
                    }
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.BoltGetResponse": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "ttl": {
                    "type": "integer"
                },
                "value": {}
            }
        },
        "models.BoltListResponse": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "description": "bucket, key",
                    "type": "string"
                }
            }
        },
        "models.ConfigPutRequest": {
            "type": "object"
        },
        "models.DirResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.File"
                    }
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "models.File": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "is_dir": {
                    "type": "boolean"
                },
                "modify_time": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "size": {
                    "type": "integer"
                },
                "write": {
                    "type": "boolean"
                }
            }
        },
        "models.NewPathRequest": {
            "type": "object",
            "properties": {
                "new_path": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "models.PathRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "models.PluginConfigUploadRequest": {
            "type": "object",
            "required": [
                "data",
                "name"
            ],
            "properties": {
                "data": {
                    "description": "base64格式的文本数据",
                    "type": "string"
                },
                "name": {
                    "description": "插件文件名",
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "models.SelectEpRequest": {
            "type": "object",
            "required": [
                "rss",
                "source"
            ],
            "properties": {
                "ep_links": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_select_ep": {
                    "type": "boolean",
                    "default": false
                },
                "rss": {
                    "type": "object",
                    "required": [
                        "url"
                    ],
                    "properties": {
                        "url": {
                            "type": "string"
                        }
                    }
                },
                "source": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Access-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
